description: null
devices:
  adjust_period: 10
  capture:
    channels: 2
    device: hw:Audio
    format: S32LE
    type: Alsa
  capture_samplerate: 44100
  chunksize: 256
  enable_rate_adjust: true
  playback:
    channels: 8
    device: hw:sndrpihifiberry
    format: S32LE
    type: Alsa
  queuelimit: 4
  rate_measure_interval: null
  resampler:
    profile: Balanced
    type: AsyncSinc
  samplerate: 192000
  silence_threshold: -100
  silence_timeout: 5
  stop_on_rate_change: null
  target_level: 511
  volume_ramp_time: null
filters: {}
mixers:
  2x8:
    channels:
      in: 2
      out: 8
    description: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 2
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 4
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 5
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 6
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 7
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
pipeline:
- bypassed: null
  description: null
  name: 2x8
  type: Mixer
processors: {}
title: S2 / DAC8x
