description: null
devices:
  adjust_period: 10
  capture:
    channels: 16
    device: hw:UltraLitemk5
    format: S24LE3
    labels: null
    link_mute_control: null
    link_volume_control: null
    stop_on_inactive: null
    type: Alsa
  capture_samplerate: 96000
  chunksize: 512
  enable_rate_adjust: false
  multithreaded: null
  playback:
    channels: 18
    device: hw:UltraLitemk5
    format: S24LE3
    type: Alsa
  queuelimit: 4
  rate_measure_interval: 1
  resampler: null
  samplerate: 96000
  silence_threshold: -100
  silence_timeout: 5
  stop_on_rate_change: false
  target_level: 1536
  volume_limit: null
  volume_ramp_time: null
  worker_threads: null
filters:
  Bass:
    description: null
    parameters:
      freq: 85
      gain: 6
      q: 0.9
      type: Lowshelf
    type: Biquad
  Treble:
    description: null
    parameters:
      freq: 6500
      gain: 0
      q: 0.7
      type: Highshelf
    type: Biquad
mixers:
  16x18:
    channels:
      in: 16
      out: 18
    description: null
    labels: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 2
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 3
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 4
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 5
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 6
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 7
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 8
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 9
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 10
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 11
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 12
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 13
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 14
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 15
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 16
      mute: false
      sources:
      - channel: 10
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 17
      mute: false
      sources:
      - channel: 11
        gain: 0
        inverted: false
        mute: false
        scale: dB
pipeline:
- bypassed: false
  channels:
  - 10
  - 11
  description: null
  names:
  - Bass
  - Treble
  type: Filter
- bypassed: false
  description: null
  name: 16x18
  type: Mixer
processors: {}
title: SPDIF
