description: null
devices:
  adjust_period: 10
  capture:
    channels: 10
    device: hw:UltraLitemk5
    format: S24LE3
    type: Alsa
  capture_samplerate: 192000
  chunksize: 256
  enable_rate_adjust: false
  playback:
    channels: 10
    device: hw:UltraLitemk5
    format: S24LE3
    type: Alsa
  queuelimit: 4
  rate_measure_interval: 1
  samplerate: 192000
  silence_threshold: -100
  silence_timeout: 5
  stop_on_rate_change: false
  target_level: 511
  volume_ramp_time: null
filters: null
mixers:
  10x10:
    channels:
      in: 10
      out: 10
    description: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 2
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 1
      mute: false
      sources:
      - channel: 3
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 2
      mute: false
      sources:
      - channel: 2
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 3
      mute: false
      sources:
      - channel: 3
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 4
      mute: false
      sources:
      - channel: 2
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 5
      mute: false
      sources:
      - channel: 3
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 6
      mute: false
      sources:
      - channel: 2
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 7
      mute: false
      sources:
      - channel: 3
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 8
      mute: false
      sources:
      - channel: 2
        gain: 0
        inverted: false
        mute: false
        scale: null
    - dest: 9
      mute: false
      sources:
      - channel: 3
        gain: 0
        inverted: false
        mute: false
        scale: null
pipeline:
- bypassed: null
  description: null
  name: 10x10
  type: Mixer
processors: null
title: Analog
